## SQL PYTHON Connect

In [1]:
#pip install sqlalchemy
#pip install pymysql

In [2]:
pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\owner\appdata\roaming\python\python313\site-packages (1.1.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from sqlalchemy import create_engine,text
import pandas as pd 
import os
import pymysql
import numpy as np

In [4]:
engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
engine1

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [5]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [6]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2         munira
3        student
4      studentb2

In [7]:
q("select * from emp")

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0  1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30
5   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0   NaN      20
6   7900   JAMES      CLERK  7698.0  1981-12-03   950.0   NaN      30
7   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0   NaN      20
8   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0   NaN      10

In [8]:
q("select * from dept")

    deptno       dname       loc
0     20.0    RESEARCH    DALLAS
1     30.0       SALES   CHICAGO
2     40.0  OPERATIONS    BOSTON
3     10.0  ACCOUNTING  NEW YORK
4     20.0    RESEARCH    DALLAS
5     30.0       SALES   CHICAGO
6     40.0  OPERATIONS    BOSTON
7     10.0  ACCOUNTING  NEW YORK
8     20.0    RESEARCH    DALLAS
9     30.0       SALES   CHICAGO
10    40.0  OPERATIONS    BOSTON

In [9]:
emp = q("select * from emp")
emp.head()

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0  1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30

In [10]:
dept = q("select * from dept")
dept.head()

   deptno       dname       loc
0    20.0    RESEARCH    DALLAS
1    30.0       SALES   CHICAGO
2    40.0  OPERATIONS    BOSTON
3    10.0  ACCOUNTING  NEW YORK
4    20.0    RESEARCH    DALLAS

In [11]:
q("select min(sal) from emp")

   min(sal)
0     800.0

In [12]:
q("select avg(sal) from emp")

      avg(sal)
0  2405.555556

In [13]:
query = 'select * from emp'
emp=pd.read_sql(query,engine1)
emp

   empno   ename        job     mgr    hiredate     sal  comm  deptno
0   1234  MUNIRA    MANAGER  7839.0  1982-01-23  5000.0   NaN      10
1   7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
2   7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0   NaN      20
3   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
4   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0   0.0      30
5   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0   NaN      20
6   7900   JAMES      CLERK  7698.0  1981-12-03   950.0   NaN      30
7   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0   NaN      20
8   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0   NaN      10

In [14]:
empdept = emp.merge(dept, on='deptno', how='inner')
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10,ACCOUNTING,NEW YORK
1,1234,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10,ACCOUNTING,NEW YORK
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
4,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS

In [15]:
empdept = emp.merge(dept, on='deptno', how='left')
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10,ACCOUNTING,NEW YORK
1,1234,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10,ACCOUNTING,NEW YORK
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
4,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS

In [16]:
empdept = emp.merge(dept, on='deptno', how='right')
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20.0,RESEARCH,DALLAS
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS
3,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS
4,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO

In [17]:
empdept.groupby('dname').size()

dname
ACCOUNTING     6
OPERATIONS     3
RESEARCH      12
SALES          6
dtype: int64

In [18]:
empdept.groupby(['dname','job']).size().reset_index()

        dname        job  0
0  ACCOUNTING      CLERK  2
1  ACCOUNTING    MANAGER  2
2  ACCOUNTING  PRESIDENT  2
3    RESEARCH    ANALYST  6
4    RESEARCH      CLERK  6
5       SALES      CLERK  3
6       SALES   SALESMAN  3

In [19]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20.0,RESEARCH,DALLAS
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS
3,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS
4,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO

In [20]:
empdept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     24 non-null     float64
 1   ename     24 non-null     object
 2   job       24 non-null     object
 3   mgr       22 non-null     float64
 4   hiredate  24 non-null     object
 5   sal       24 non-null     float64
 6   comm      3 non-null      float64
 7   deptno    27 non-null     float64
 8   dname     27 non-null     object
 9   loc       27 non-null     object
dtypes: float64(5), object(5)
memory usage: 2.2+ KB

In [21]:
import datetime as dt

In [22]:
empdept['hiredate'] = pd.to_datetime(empdept['hiredate']) #dt.date

In [23]:
empdept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     24 non-null     float64
 1   ename     24 non-null     object
 2   job       24 non-null     object
 3   mgr       22 non-null     float64
 4   hiredate  24 non-null     datetime64[ns]
 5   sal       24 non-null     float64
 6   comm      3 non-null      float64
 7   deptno    27 non-null     float64
 8   dname     27 non-null     object
 9   loc       27 non-null     object
dtypes: datetime64[ns](1), float64(5), object(4)
memory usage: 2.2+ KB

In [24]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20.0,RESEARCH,DALLAS
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS
3,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS
4,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO

In [25]:
empdept['hireyear']=empdept['hiredate'].dt.year
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
0,7369.0,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20.0,RESEARCH,DALLAS,1980.0
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
3,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS,1981.0
4,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO,1981.0

In [26]:
empdept[empdept['hireyear'] > 1980]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
3,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS,1981.0
4,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO,1981.0
5,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30.0,SALES,CHICAGO,1981.0
7,1234.0,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
8,7839.0,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10.0,ACCOUNTING,NEW YORK,1981.0
9,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
11,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
12,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
13,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS,1981.0
14,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO,1981.0
15,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30.0,SALES,CHICAGO,1981.0
17,1234.0,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
18,7839.0,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10.0,ACCOUNTING,NEW YORK,1981.0
19,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
21,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
22,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
23,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS,1981.0
24,7844.0,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO,1981.0
25,7900.0,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30.0,SALES,CHICAGO,1981.0

In [27]:
empdept[empdept['hireyear'] >= 1982]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
7,1234.0,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
9,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
11,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
12,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
17,1234.0,MUNIRA,MANAGER,7839.0,1982-01-23,5000.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
19,7934.0,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10.0,ACCOUNTING,NEW YORK,1982.0
21,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
22,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0

In [28]:
empdept[(empdept['hireyear']>=1981) & (empdept['dname']=='RESEARCH')]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
3,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS,1981.0
11,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
12,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
13,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS,1981.0
21,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
22,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
23,7902.0,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20.0,RESEARCH,DALLAS,1981.0

In [29]:
empdept[(empdept['hiredate'].dt.year >= 1982) & (empdept['dname']=='RESEARCH')]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
1,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
2,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
11,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
12,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0
21,7788.0,SCOTT,ANALYST,7566.0,1982-12-09,3000.0,NaN,20.0,RESEARCH,DALLAS,1982.0
22,7876.0,ADAMS,CLERK,7788.0,1983-01-12,1100.0,NaN,20.0,RESEARCH,DALLAS,1983.0

In [30]:
today = pd.to_datetime('today')
today

Timestamp('2026-05-15 22:04:49.404893')

In [31]:
import numpy as np

In [32]:
(today - empdept['hiredate']) / np.timedelta64(1, 'D')
# empdept.head()

0     16585.920016
1     15863.920016
2     15829.920016
3     16234.920016
4     16320.920016
5     16234.920016
6              NaN
7     16183.920016
8     16250.920016
9     16183.920016
10    16585.920016
11    15863.920016
12    15829.920016
13    16234.920016
14    16320.920016
15    16234.920016
16             NaN
17    16183.920016
18    16250.920016
19    16183.920016
20    16585.920016
21    15863.920016
22    15829.920016
23    16234.920016
24    16320.920016
25    16234.920016
26             NaN
Name: hiredate, dtype: float64

In [33]:
months=((today - empdept['hiredate']) / np.timedelta64(1, 'D') / 30.44)
months = months.fillna(0).astype(int)
print(months)

0     544
1     521
2     520
3     533
4     536
5     533
6       0
7     531
8     533
9     531
10    544
11    521
12    520
13    533
14    536
15    533
16      0
17    531
18    533
19    531
20    544
21    521
22    520
23    533
24    536
25    533
26      0
Name: hiredate, dtype: int64

In [34]:
((today - empdept['hiredate']) / np.timedelta64(1, 'D') / 30.44).astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
empdept['monthServed']=((today - empdept['hiredate']) / np.timedelta64(1, 'D') / 30.44).astype(int)
empdept.head()

In [ ]:
empdept.drop(columns='months_diff', inplace=True)

In [ ]:
empdept